version: '3'
services:
  ubuntu-jammy-desktop:
    ports:
      - '6901:6901'
    environment:
      - VNC_PW=zlSvLT5E23ARKq5HESl0zzMT5wUdQETSDi+dutUsWzU=
    image: 'kasmweb/ubuntu-jammy-desktop:1.14.0'
    volumes:
      - /data/vasp.6.3.0.tgz:/app/vasp.6.3.0.tgz
      - /data/makefile.tgz:/app/makefile.include
